name: "nominal"
lidar:
  geometry:
    r_min: 0.05
    r_max: 10.0
    theta_fov: 4.71238898038469  # 270 degrees in radians
    delta_theta: 0.008726646259971648  # 0.5 degrees in radians
    f_scan: 15.0
  distortion:
    sigma_r: 0.0
    p_miss: 0.0
    p_ghost: 0.0
perception:
  eta_cpl: 1.0
  sigma_map: 0.0
dynamics:
  v_agv_max: 1.5
  a_agv_max: 1.0
  omega_agv_max: 1.0
  T_horizon: 120.0
